### ISSUE TITLE
Error with vite build + new mqtt library

### ISSUE THREAD

**Issue by linomp** [MutilatedPeripherals/svelte-qr-mqtt#7]
This only happens with `yarn build`, not `yarn dev`.

Error dump:

```
"connect" is not exported by "node_modules/node-stdlib-browser/esm/mock/empty.js", imported by "node_modules/u8-mqtt/esm/node/index.js".             
file: C:/Users/LM2P/WebstormProjects/react-qr-mqtt/node_modules/u8-mqtt/esm/node/index.js:1:9                                                        
1: import { connect } from 'node:net';                                                                                                               
RollupError: "connect" is not exported by "node_modules/node-stdlib-browser/esm/mock/empty.js", imported by "node_modules/u8-mqtt/esm/node/index.js".
    at error (file:///C:/Users/LM2P/WebstormProjects/react-qr-mqtt/node_modules/rollup/dist/es/shared/node-entry.js:2095:30)
    at Module.error (file:///C:/Users/LM2P/WebstormProjects/react-qr-mqtt/node_modules/rollup/dist/es/shared/node-entry.js:13145:16)
    at Module.traceVariable (file:///C:/Users/LM2P/WebstormProjects/react-qr-mqtt/node_modules/rollup/dist/es/shared/node-entry.js:13530:29)
    at ModuleScope.findVariable (file:///C:/Users/LM2P/WebstormProjects/react-qr-mqtt/node_modules/rollup/dist/es/shared/node-entry.js:12009:39)
    at ChildScope.findVariable (file:///C:/Users/LM2P/WebstormProjects/react-qr-mqtt/node_modules/rollup/dist/es/shared/node-entry.js:6824:38)
    at ClassBodyScope.findVariable (file:///C:/Users/LM2P/WebstormProjects/react-qr-mqtt/node_modules/rollup/dist/es/shared/node-entry.js:6824:38)
    at ChildScope.findVariable (file:///C:/Users/LM2P/WebstormProjects/react-qr-mqtt/node_modules/rollup/dist/es/shared/node-entry.js:6824:38)
    at FunctionScope.findVariable (file:///C:/Users/LM2P/WebstormProjects/react-qr-mqtt/node_modules/rollup/dist/es/shared/node-entry.js:6824:38)
    at ChildScope.findVariable (file:///C:/Users/LM2P/WebstormProjects/react-qr-mqtt/node_modules/rollup/dist/es/shared/node-entry.js:6824:38)
    at ReturnValueScope.findVariable (file:///C:/Users/LM2P/WebstormProjects/react-qr-mqtt/node_modules/rollup/dist/es/shared/node-entry.js:6824:38)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by linomp** [comment]
Fixed by using the ["web bundler"](https://github.com/shanewholloway/js-u8-mqtt/blob/master/docs/use_from_web_bundler.md) import mode of u8-mqtt, instead of the NodeJS way

Then it was necessary to [specify the target as `esnext`](https://github.com/vitejs/vite/issues/6985#issuecomment-1044375490).
